### ISSUE TITLE
is there a better way to get big files on s3?

### ISSUE THREAD

**Issue by loveJasmine** [vaexio/dash-120million-taxi-app#3] opened 2020-08-03 10:01 UTC
we cannot download it

**Comment by JovanVeljanoski** [comment] 2020-08-03 10:20
Without code examples / errors we really can't help you. 
I just tested it out, and it works.. 

```
import vaex
file_path = 's3://vaex/taxi/yellow_taxi_2012_zones.hdf5?anon=true'
df = vaex.open(file_path)

print(df)
```

The speed with which you get the data depends on your location and internet connection I guess.

**Comment by loveJasmine** [comment] 2020-08-03 14:54
maybe we can use google driver or gitlfs?

**Comment by JovanVeljanoski** [comment] 2020-08-04 08:10
You can download the dataset like this:
```
import vaex
file_path = 's3://vaex/taxi/yellow_taxi_2012_zones.hdf5?anon=true'
df = vaex.open(file_path)

for col in df.column_names:
    df.nop(col, progress=True))
```

After that is finished, the dataset (hdf5 file) will be in /your_home/.vaex/file-cache/s3/vaex/taxi/

If you want, you can than host it where it is convenient for you.

**Closed by JovanVeljanoski** 2020-08-04 08:10 UTC

**Comment by lakemike** [comment] 2021-05-15 14:25
I tried this, but get an error:
`ERROR:MainThread:vaex.execution:error in task, flush task queue
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/jupyter-env/lib/python3.9/site-packages/vaex/execution.py", line 176, in execute_async
    raise RuntimeError(f'Oops, requesting column {column} from dataset, but it does not exist')
RuntimeError: Oops, requesting column o from dataset, but it does not exist`

**Comment by mtwichan** [comment] 2021-07-10 19:26
I'm also getting the same error as @lakemike when running the `getdata.py` file.

I wonder if this is a bug?

I tried checking the columns in the dataset and they looked correct.

As a test case I tried running the `.nop` function on a single column that I verified exists: 
```
import vaex
import os
# Open the main data
taxi_path = 's3://vaex/taxi/yellow_taxi_2012_zones.hdf5?anon=true'
# override the path, e.g. $ export TAXI_PATH=/data/taxi/yellow_taxi_2012_zones.hdf5
taxi_path = os.environ.get('TAXI_PATH', taxi_path)
df_original = vaex.open(taxi_path)

# test code
df_original.nop("pickup_longitude")
```

It gives me the following error:
```
ERROR:MainThread:vaex.execution:error in task, flush task queue
Traceback (most recent call last):
  File "C:\Users\matthew.chan\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\execution.py", line 193, in execute_async
    raise RuntimeError(f'Oops, requesting column {column} from dataset, but it does not exist')
RuntimeError: Oops, requesting column i from dataset, but it does not exist
ERROR:vaex.execution:error in task, flush task queue
Traceback (most recent call last):
  File "C:\Users\matthew.chan\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\execution.py", line 193, in execute_async
    raise RuntimeError(f'Oops, requesting column {column} from dataset, but it does not exist')
RuntimeError: Oops, requesting column i from dataset, but it does not exist
Traceback (most recent call last):
  File "C:\Users\matthew.chan\Desktop\zyphr_code\dash-120million-taxi-app\getdata.py", line 24, in <module>
    df_original.nop("pickup_longitude")
  File "C:\Users\matthew.chan\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\dataframe.py", line 443, in nop
    return self.map_reduce(map, reduce, expressions, delay=delay, progress=progress, name='nop', to_numpy=False)
  File "C:\Users\matthew.chan\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\dataframe.py", line 393, in map_reduce
    return self._delay(delay, task)
  File "C:\Users\matthew.chan\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\dataframe.py", line 1537, in _delay
    self.execute()
  File "C:\Users\matthew.chan\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\dataframe.py", line 375, in execute
    just_run(self.execute_async())
  File "C:\Users\matthew.chan\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\asyncio.py", line 35, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\matthew.chan\AppData\Local\Programs\Python\Python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\Users\matthew.chan\AppData\Local\Programs\Python\Python39\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\matthew.chan\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\matthew.chan\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\dataframe.py", line 380, in execute_async
    await self.executor.execute_async()
  File "C:\Users\matthew.chan\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\execution.py", line 193, in execute_async
    raise RuntimeError(f'Oops, requesting column {column} from dataset, but it does not exist')
RuntimeError: Oops, requesting column i from dataset, but it does not exist
```

What's also strange, is that it the letter in the error message changes every time I run the code. 

Ex: "... requesting column <letter> ..."

I'm using Python 3.9.5 on Windows. Python dependencies can be found below:

```
adal==1.2.7
adlfs==0.7.7
aiohttp==3.7.4.post0
ansi2html==1.6.0
aplus==0.11.0
appdirs==1.4.4
argon2-cffi==20.1.0
astropy==4.2.1
async-generator==1.10
async-timeout==3.0.1
atomicwrites==1.4.0
attrs==21.2.0
azure-core==1.15.0
azure-datalake-store==0.0.52
azure-identity==1.6.0
azure-storage-blob==12.8.1
backcall==0.2.0
black==21.6b0
blake3==0.1.8
bleach==3.3.0
bokeh==2.3.2
bqplot==0.12.29
Brotli==1.0.9
cachetools==4.2.2
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==8.0.1
cloudpickle==1.6.0
colorama==0.4.4
colorcet==2.0.6
cryptography==3.3.1
cycler==0.10.0
dash==1.20.0
dash-bootstrap-components==0.12.2
dash-core-components==1.16.0
dash-extensions==0.0.53
dash-html-components==1.1.3
dash-renderer==1.9.1
dash-table==4.11.3
dask==2021.6.2
datashader==0.13.0
datashape==0.5.2
decorator==5.0.9
defusedxml==0.7.1
distlib==0.3.1
distributed==2021.6.2
entrypoints==0.3
filelock==3.0.12
Flask==2.0.1
Flask-Caching==1.10.1
Flask-Compress==1.9.0
flask-server-timing==0.1.2
frozendict==2.0.3
fsspec==2021.6.1
future==0.18.2
gunicorn==20.0.4
h5py==3.3.0
HeapDict==1.0.1
holoviews==1.14.4
idna==2.10
iniconfig==1.1.1
ipydatawidgets==4.2.0
ipykernel==5.5.5
ipyleaflet==0.14.0
ipympl==0.7.0
ipython==7.25.0
ipython-genutils==0.2.0
ipyvolume==0.5.2
ipyvue==1.5.0
ipyvuetify==1.7.0
ipywebrtc==0.6.0
ipywidgets==7.6.3
isodate==0.6.0
itsdangerous==2.0.1
jedi==0.18.0
Jinja2==3.0.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.12
jupyter-console==6.4.0
jupyter-core==4.7.1
jupyter-dash==0.4.0
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
kiwisolver==1.3.1
llvmlite==0.36.0
locket==0.2.1
Markdown==3.3.4
MarkupSafe==2.0.1
matplotlib==3.4.2
matplotlib-inline==0.1.2
mistune==0.8.4
more-itertools==8.8.0
msal==1.12.0
msal-extensions==0.3.0
msgpack==1.0.2
msrest==0.6.21
multidict==5.1.0
multipledispatch==0.6.0
mypy-extensions==0.4.3
natsort==7.1.0
nbclient==0.5.3
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.4.0
numba==0.53.1
numpy==1.20.3
oauthlib==3.1.1
packaging==20.9
pandas==1.1.2
pandocfilters==1.4.3
panel==0.11.3
param==1.10.1
parso==0.8.2
partd==1.2.0
pathspec==0.8.1
pickleshare==0.7.5
Pillow==8.2.0
pip-autoremove==0.9.1
pip-chill==1.0.0
plotly==4.14.3
pluggy==0.13.1
portalocker==1.7.1
progressbar2==3.53.1
prometheus-client==0.11.0
prompt-toolkit==3.0.19
psutil==5.8.0
py==1.10.0
pyarrow==3.0.0
pycparser==2.20
pyct==0.4.8
pyerfa==2.0.0
Pygments==2.9.0
PyJWT==1.7.1
pyparsing==2.4.7
pyrsistent==0.18.0
pytest==6.2.1
python-dateutil==2.8.1
python-dotenv==0.14.0
python-utils==2.5.6
pythreejs==2.3.0
pytz==2021.1
pyviz-comms==2.0.2
pywin32==301
pywinpty==1.1.3
PyYAML==5.4.1
pyzmq==22.1.0
qtconsole==5.1.1
QtPy==1.9.0
redis==3.0.1
redis-py-cluster==2.0.0
regex==2021.4.4
requests==2.25.1
requests-oauthlib==1.3.0
retrying==1.3.3
scipy==1.7.0
Send2Trash==1.7.1
six==1.16.0
sortedcontainers==2.4.0
tabulate==0.8.9
tblib==1.7.0
terminado==0.10.1
testpath==0.5.0
toml==0.10.2
toolz==0.11.1
tornado==6.1
tqdm==4.61.1
traitlets==5.0.5
traittypes==0.2.1
typed-ast==1.4.3
typing-extensions==3.10.0.0
urllib3==1.26.4
vaex==4.3.0
vaex-astro==0.8.2
vaex-core==4.3.0.post1
vaex-hdf5==0.8.0
vaex-jupyter==0.6.0
vaex-ml==0.12.0
vaex-server==0.5.0
vaex-viz==0.5.0
virtualenv==20.4.7
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.0.1
widgetsnbextension==3.5.1
xarray==0.18.2
yarl==1.6.3
zict==2.0.0
```

**Comment by maartenbreddels** [comment] 2021-07-10 20:18
My guess is you should pass a list, since I see vaex trying to find single
letter columns, it's likely interpreting the string as a sequence of
characters

(from mobile phone)

**Comment by maartenbreddels** [comment] 2021-07-10 20:19
Jovan: is this a backwards incompatible change, if so, we should fix that I
think

(from mobile phone)

**Comment by mtwichan** [comment] 2021-07-10 20:47
@maartenbreddels it looks like your intuition was correct, it worked! 

Here's the version with your fix:

```
import vaex
import os
# Open the main data
taxi_path = 's3://vaex/taxi/yellow_taxi_2012_zones.hdf5?anon=true'
# override the path, e.g. $ export TAXI_PATH=/data/taxi/yellow_taxi_2012_zones.hdf5
taxi_path = os.environ.get('TAXI_PATH', taxi_path)
df_original = vaex.open(taxi_path)

# Make sure the data is cached locally
used_columns = ['pickup_longitude',
                'pickup_latitude',
                'dropoff_longitude',
                'dropoff_latitude',
                'total_amount',
                'trip_duration_min',
                'trip_speed_mph',
                'pickup_hour',
                'pickup_day',
                'dropoff_borough',
                'dropoff_zone',
                'pickup_borough',
                'pickup_zone']
for col in used_columns:
    print(f'Making sure column "{col}" is cached...')
    df_original.nop([col], progress=True) #wrap col in a list
```

The blob of code above is used in `app.py`, just a heads up.

Thanks for your help!

**Comment by JovanVeljanoski** [comment] 2021-07-10 21:06
Hi, 

yes I just checked and some changes were done to `dataframe.nop` so that now it requires the 1st argument of `nop` to be a list. I don't think this was intended, i think the original intention was to support both lists and single expressions (i guess). 

Having said that, this repository does contain a requirements file which clearly specifies the vaex-core and vaex-hdf5 versions required to run this example.. 

In any case, I will try to fix this issue when I can.
